### ISSUE TITLE
Update code style

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/tbil-la#125]
Code should be updated to conform to the coding style listed in the Readme. In particular, $ delimiters should be removed. This is probably going to help with #97 when we finally take the plunge and do that.

**Comment by siwelwerd** [comment]
I believe in fdf9ea69.. I excised the $ signs from the activities.tex files, which are likely the main culprits. For future reference: first, I searched for any $$...$$ expressions. Once those are eradicated, a "simple" vi regex (namely, :%s/\$\(.\{-}\)\$/\\(\1\\)/g ) does the trick, though it will likely break if there are any escaped dollar signs.

**Comment by StevenClontz** [comment]
Closing this - my XML styling isn't super-great in the first pass, but long-term I plan to have PreTeXt-CLI automatically format the XML nicely anyway.
